config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/', to: 'static_pages#home'
  get '/new', to: 'users#new'
  post '/new', to: 'users#create', as: "create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create


    @user = User.new
    # puts "<====>"
    # puts params
    # puts "<====>"
    @user.username = params["user"]
    @user.email = params["email"]
    @user.bio = params["bio"]
    @user.save
    # User.create(username:a, email:b, bio:c)
    redirect_to "/"

# A utiliser avec le formulaire form_for
    # @user = User.new
    # # puts "<====>"
    # # puts params
    # # puts "<====>"
    # @user.username = params["user"]["username"]
    # @user.email = params["user"]["email"]
    # @user.bio = params["user"]["bio"]
    # @user.save
    # # User.create(username:a, email:b, bio:c)
    # redirect_to "/"

  end

  def user

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <title>HerokuFormulaire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<p>Pour créer un utilisateur, c'est par <%= link_to 'ici',new_path %></p>

app/views/users/new.html.erb
<center>

  <h1>Bienvenue sur la page d'enregistrement</h1>


  <!-- <form action="<%= create_path %>"method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="user" placeholder="username">
  <input type="email" name="email" placeholder="email">
  <textarea name="bio" rows="8" cols="30" placeholder="bio"></textarea>
  <input type="submit" value="Envoyer le formulaire">
</form>
-->

<div class="container">

<%= form_tag url_for(action: 'create'), method: "post",class: 'form-group' do %>

  <%= label_tag 'User' %>

  <%= text_field_tag 'user'  %>
<br /> <br />
<div class="form-group">
<%= label_tag 'Email' %>
<%= text_field_tag 'email', '', class: 'form-control'%>
</div>

<br /> <br />

<%= label_tag 'Bio' %>
<%= text_area_tag 'bio'%>
<br /> <br />

<%= submit_tag "Create Post" %>

<% end %>

</div>



<!-- <%= form_for :user do |f| %>
Username: <%= f.text_field :username %><br />
Email : <%= f.text_field :email %><br />
Bio : <%= f.text_area :bio %><br />
<%= f.submit %>
<% end %> -->
</center>